name: corticalmixup
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - matplotlib=3.7.1
  - numpy=1.23.5
  - pandas=1.5.2
  - python=3.10.10
  - pytorch=2.0.0
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - torchvision=0.15.0
  - iterative-stratification
  - git+git://https://github.com/neurospin-deepinsight/surfify@master